public class UserWrapper {
    public Integer total;
    public Integer skip;
    public List<usersWrp> userInfo;

    public class usersWrp {
        public string username;
        public string firstName;
        public string lastName;
        public string maidenName;
        public integer age;
        public string gender;
        public string email;
        public string phone;
        public string birthDate;
        public string password;

    }

}